### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by kariavka** [mgood/flask-debugtoolbar#77]
UnicodeDecodeError
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 40: ordinal not in range(128)

Traceback (most recent call last)
File "/home/livarava/.env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/home/livarava/.env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/livarava/.env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/home/livarava/.env/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
response = self.process_response(response)
File "/home/livarava/.env/lib/python2.7/site-packages/flask/app.py", line 1691, in process_response
response = handler(response)
File "/home/livarava/.env/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 196, in process_response
toolbar_html = self.debug_toolbars[real_request].render_toolbar()
File "/home/livarava/.env/lib/python2.7/site-packages/flask_debugtoolbar/toolbar.py", line 45, in render_toolbar
return template.render(**context)
File "/home/livarava/.env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
return self.environment.handle_exception(exc_info, True)
File "/home/livarava/.env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/livarava/.env/lib/python2.7/site-packages/flask_debugtoolbar/templates/base.html", line 50, in top-level template code
{{ panel.content()|safe }}
File "/home/livarava/.env/lib/python2.7/site-packages/flask_debugtoolbar_lineprofilerpanel/panels.py", line 126, in content
'stats': processed_line_stats
File "/home/livarava/.env/lib/python2.7/site-packages/flask_debugtoolbar/panels/__init__.py", line 28, in render
return template.render(**context)
File "/home/livarava/.env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
return self.environment.handle_exception(exc_info, True)
File "/home/livarava/.env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
reraise(exc_type, exc_value, tb)
File "/home/livarava/.env/lib/python2.7/site-packages/flask_debugtoolbar_lineprofilerpanel/templates/content.html", line 72, in top-level template code
<td><pre>{{ line }}</pre></td>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 40: ordinal not in range(128)

**Comment by kariavka** [comment]
It is an issue of Flask DebugToolbar Line Profiler. Sorry, guys.
