### ISSUE TITLE
Error for endpoints

### ISSUE THREAD

**Issue by Garito** [mgood/flask-debugtoolbar#82]
Hi!
If I try to define a route by specify an endpoint to allow every method it fails like a champ. Here the full traceback:
```python
Traceback (most recent call last):
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask/app.py", line 1691, in process_response
    response = handler(response)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_debugtoolbar/__init__.py", line 223, in process_response
    toolbar_html = toolbar.render_toolbar()
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_debugtoolbar/toolbar.py", line 46, in render_toolbar
    return template.render(**context)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_debugtoolbar/templates/base.html", line 50, in top-level template code
    {{ panel.content()|safe }}
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_debugtoolbar/panels/route_list.py", line 33, in content
    'routes': self.routes,
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_debugtoolbar/panels/__init__.py", line 30, in render
    return template.render(**context)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_debugtoolbar/templates/panels/route_list.html", line 17, in top-level template code
    <td>{{ route.methods|sort|join(', ') }}</td>
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/jinja2/filters.py", line 265, in do_sort
    return sorted(value, key=sort_func, reverse=reverse)
TypeError: 'NoneType' object is not iterable
```

Could someone point me how to solve this?

Thanks

**Comment by mgood** [comment]
Sorry, yeah that looks like a bug. I guess most people aren't using that feature and pass a list of all the methods they want it to handle. But since Flask's routing supports it, the toolbar should too.

As a workaround, you could pass a list of the methods you want it to support, e.g. `['GET', 'POST', 'PUT', 'DELETE']` works in most cases.

**Comment by jeffwidman** [comment]
@Garito is this still an issue with the latest version of Flask/Werkzeug? 

I haven't dug into the problem here, but there's been several changes to the Flask/Werkzeug routing, so want to verify it's still an issue before looking into it further.

**Comment by Garito** [comment]
Sorry I can't even remember what is this all about...

**Comment by jeffwidman** [comment]
No worries, closing for now, if it's still a problem someone else will report it.
